/* tslint:disable */
/* eslint-disable */
/**
/* This file was automatically generated from pydantic models by running pydantic2ts.
/* Do not modify it by hand - just update the pydantic models and then re-run the script
*/

export type Part = TextPart | FilePart | DataPart;
/**
 * Identifies the sender of the message. `user` for the client, `agent` for the service.
 */
export type Role = "agent" | "user";
/**
 * Defines the lifecycle states of a Task.
 */
export type TaskState =
  | "submitted"
  | "working"
  | "input-required"
  | "completed"
  | "canceled"
  | "failed"
  | "rejected"
  | "auth-required"
  | "unknown";

export interface MemoryContent {
  memory_text: string;
}
export interface MessageContent {
  message_text: string;
}
export interface Room {
  room_id?: string;
  room_name: string;
  room_owner_id: string;
  room_owner_name: string;
  room_agent_set?: {
    [k: string]: string;
  };
  room_created_at?: string;
  extend_info?: unknown;
}
export interface RoomAgentMessage {
  room_id: string;
  message_id: string;
  related_message_id?: string | null;
  agent_id: string;
  agent_name: string;
  message_content: Task;
  message_created_at?: string;
  extend_info?: unknown;
}
/**
 * Represents a single, stateful operation or conversation between a client and an agent.
 */
export interface Task {
  artifacts?: Artifact[] | null;
  contextId: string;
  history?: Message[] | null;
  id: string;
  kind?: "task";
  metadata?: {
    [k: string]: unknown;
  } | null;
  status: TaskStatus;
}
/**
 * Represents a file, data structure, or other resource generated by an agent during a task.
 */
export interface Artifact {
  artifactId: string;
  description?: string | null;
  extensions?: string[] | null;
  metadata?: {
    [k: string]: unknown;
  } | null;
  name?: string | null;
  parts: Part[];
  [k: string]: unknown;
}
/**
 * Represents a text segment within a message or artifact.
 */
export interface TextPart {
  kind?: "text";
  metadata?: {
    [k: string]: unknown;
  } | null;
  text: string;
  [k: string]: unknown;
}
/**
 * Represents a file segment within a message or artifact. The file content can be
 * provided either directly as bytes or as a URI.
 */
export interface FilePart {
  file: FileWithBytes | FileWithUri;
  kind?: "file";
  metadata?: {
    [k: string]: unknown;
  } | null;
  [k: string]: unknown;
}
/**
 * Represents a file with its content provided directly as a base64-encoded string.
 */
export interface FileWithBytes {
  bytes: string;
  mimeType?: string | null;
  name?: string | null;
  [k: string]: unknown;
}
/**
 * Represents a file with its content located at a specific URI.
 */
export interface FileWithUri {
  mimeType?: string | null;
  name?: string | null;
  uri: string;
  [k: string]: unknown;
}
/**
 * Represents a structured data segment (e.g., JSON) within a message or artifact.
 */
export interface DataPart {
  data: {
    [k: string]: unknown;
  };
  kind?: "data";
  metadata?: {
    [k: string]: unknown;
  } | null;
  [k: string]: unknown;
}
/**
 * Represents a single message in the conversation between a user and an agent.
 */
export interface Message {
  contextId?: string | null;
  extensions?: string[] | null;
  kind?: "message";
  messageId: string;
  metadata?: {
    [k: string]: unknown;
  } | null;
  parts: Part[];
  referenceTaskIds?: string[] | null;
  role: Role;
  taskId?: string | null;
  [k: string]: unknown;
}
/**
 * Represents the status of a task at a specific point in time.
 */
export interface TaskStatus {
  message?: Message | null;
  state: TaskState;
  timestamp?: string | null;
  [k: string]: unknown;
}
export interface RoomMemory {
  room_id: string;
  memory_id: string;
  memory_content: MemoryContent;
  memory_created_at?: string;
  extend_info?: unknown;
}
/**
 * Unified room message format for both user and agent messages
 */
export interface RoomMessage {
  message_id: string;
  message_type: string;
  message_content: string;
  message_created_at: string;
  user_name?: string | null;
  agent_name?: string | null;
}
export interface RoomUserMessage {
  room_id: string;
  message_id: string;
  related_message_id?: string | null;
  user_id: string;
  user_name: string;
  message_content: MessageContent;
  message_created_at?: string;
  extend_info?: unknown;
}
