#!/usr/bin/env python3
"""Render the default-agent section of docker-compose.yml from agents.yaml.

`agents.yaml` is the single source of truth for which default agents exist and
their service name / port / build directory. This script generates the matching
docker-compose service blocks (one per *enabled* agent) plus the one-shot
`registrar` service, and writes them into docker-compose.yml between two marker
comments. That way you only ever edit agents.yaml; the Compose file follows.

It also generates the backend's agent-host-port exclusion list, which keeps the
stack's own agents out of local agent discovery.

Usage:
    python default_agents/render_compose.py           # rewrite the generated regions
    python default_agents/render_compose.py --check    # exit 1 if out of sync (CI)

Each generated region is delimited by a BEGIN/END marker pair below. Everything
outside those markers (mongo, redis, the rest of backend, frontend, the x-agent
anchor, the volumes block) is left untouched.
"""

from __future__ import annotations

import argparse
import os
import sys
from collections.abc import Sequence
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "default_agents" / "agents.yaml"
COMPOSE_PATH = REPO_ROOT / "docker-compose.yml"

BEGIN_MARKER = (
    "  # >>> BEGIN default agents "
    "(generated by default_agents/render_compose.py — do not edit by hand) >>>"
)
END_MARKER = "  # <<< END default agents <<<"

# The backend's discovery exclusion list is generated too: it must name exactly
# the host ports this stack publishes for its own agents.
PORTS_BEGIN_MARKER = (
    "      # >>> BEGIN default-agent host ports "
    "(generated by default_agents/render_compose.py — do not edit by hand) >>>"
)
PORTS_END_MARKER = "      # <<< END default-agent host ports <<<"

BACKEND_URL = "http://backend:8000"
API_PREFIX = "${HYBRO_API_PREFIX:-/api/v1}"

# Only these CLI-projected settings are forwarded into default-agent containers. Backend/frontend secrets (Mongo creds, WEBHOOK_SIGNING_KEY,
# CLERK_SECRET_KEY, etc.) MUST NOT be exposed here — see the
# comment on the x-agent anchor in docker-compose.yml. Models come from setup.
AGENT_ENV_INTERPOLATIONS: tuple[tuple[str, str], ...] = (
    ("HYBRO_AGENT_CONFIG", ""),
)

# The registrar only needs the shared service token; every other value is set
# statically below.
REGISTRAR_ENV_INTERPOLATIONS: tuple[tuple[str, str], ...] = (
    ("AGENT_REGISTRAR_TOKEN", ""),
)


def _env_line(key: str, default: str) -> str:
    """Render an `environment:` list entry with a Compose-safe default."""
    return f"      - {key}=${{{key}:-{default}}}"


def load_enabled_agents(manifest_path: Path = MANIFEST_PATH) -> dict[str, dict]:
    """Return enabled agents from the manifest, preserving file order."""
    data = yaml.safe_load(manifest_path.read_text(encoding="utf-8")) or {}
    agents = data.get("agents", {}) or {}
    enabled: dict[str, dict] = {}
    for name, spec in agents.items():
        spec = spec or {}
        if not spec.get("enabled", True):
            continue
        for field in ("dir", "service", "port"):
            if spec.get(field) in (None, ""):
                raise ValueError(f"agent '{name}' is missing required field '{field}'")
        enabled[name] = spec
    return enabled


def render_region(agents: dict[str, dict]) -> str:
    """Render the inner text between the markers (markers excluded)."""
    lines: list[str] = [
        "  # ---- Default agents (generated from default_agents/agents.yaml) ----"
    ]

    for spec in agents.values():
        service = spec["service"]
        port = spec["port"]
        agent_dir = spec["dir"]
        lines += [
            "",
            f"  {service}:",
            "    <<: *agent",
            "    build:",
            "      context: ./default_agents",
            "      dockerfile: Dockerfile",
            "      args:",
            f"        AGENT_DIR: {agent_dir}",
            "    environment:",
            f"      - SERVER_PORT={port}",
            f"      - SERVER_DOMAIN={service}",
        ]
        # Filtered agent-only projection from the CLI's JSON configuration.
        lines += [_env_line(key, default) for key, default in AGENT_ENV_INTERPOLATIONS]
        lines += [
            "    ports:",
            f'      - "{port}:{port}"',
        ]

    lines += [
        "",
        "  # One-shot: registers every enabled agent with the backend, then exits.",
        "  # Uses filtered interpolation instead of env_file so backend secrets",
        "  # (Mongo, Clerk, webhook signing key, ...) never reach this container.",
        "  registrar:",
        "    build:",
        "      context: ./default_agents",
        "      dockerfile: Dockerfile.registrar",
        "    environment:",
        f"      - BACKEND_URL={BACKEND_URL}",
        f"      - API_PREFIX={API_PREFIX}",
    ]
    lines += [_env_line(key, default) for key, default in REGISTRAR_ENV_INTERPOLATIONS]
    lines += [
        '    restart: "no"',
        "    depends_on:",
        "      backend:",
        "        condition: service_healthy",
    ]
    for spec in agents.values():
        lines += [
            f"      {spec['service']}:",
            "        condition: service_started",
        ]

    return "\n".join(lines)


def render_ports_region(agents: dict[str, dict]) -> str:
    """Render the backend's list of this stack's own agent host ports.

    Discovery scans the Docker host for A2A agents, and this stack publishes
    every enabled agent's port there, so the scanner finds the stack's own
    agents served over ``host.docker.internal``. Nothing else can occupy those
    ports (the stack already binds them), so excluding them loses no real host
    agent.
    """
    ports = ",".join(str(spec["port"]) for spec in agents.values())
    return (
        "      # Every agent below publishes its host port, so discovery over\n"
        "      # host.docker.internal would find this stack's own agents and register a\n"
        "      # second copy of each under its host URL.\n"
        f"      - LOCAL_AGENT_DISCOVERY_EXCLUDED_PORTS={ports}"
    )


def render_regions(agents: dict[str, dict]) -> list[tuple[str, str, str]]:
    """Every generated region as ``(begin marker, end marker, rendered text)``."""
    return [
        (PORTS_BEGIN_MARKER, PORTS_END_MARKER, render_ports_region(agents)),
        (BEGIN_MARKER, END_MARKER, render_region(agents)),
    ]


def _marker_line(lines: list[str], marker: str) -> int:
    """Index of the line that is exactly ``marker``."""
    for index, line in enumerate(lines):
        if line.rstrip() == marker:
            return index
    raise ValueError(
        "docker-compose.yml is missing the generated-region marker "
        f"({marker!r})"
    )


def build_expected(
    compose_text: str,
    regions: Sequence[tuple[str, str, str]],
) -> str:
    """Return the full compose file with every generated region replaced."""
    lines = compose_text.splitlines()
    spans: list[tuple[int, int, str]] = []
    for begin, end, rendered in regions:
        start = _marker_line(lines, begin)
        stop = _marker_line(lines, end)
        if stop < start:
            raise ValueError(f"END marker appears before BEGIN marker: {end!r}")
        spans.append((start, stop, rendered))
    spans.sort(key=lambda span: span[0])

    rebuilt: list[str] = []
    cursor = 0
    for start, stop, rendered in spans:
        if start < cursor:
            raise ValueError("Generated regions overlap in docker-compose.yml")
        rebuilt += lines[cursor : start + 1]
        rebuilt.append(rendered)
        cursor = stop
    rebuilt += lines[cursor:]

    trailing = "\n" if compose_text.endswith("\n") else ""
    return "\n".join(rebuilt) + trailing


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if docker-compose.yml is out of sync with agents.yaml.",
    )
    parser.add_argument(
        "--manifest",
        default=os.fspath(MANIFEST_PATH),
        help="Agent manifest to render from (defaults to the repository's).",
    )
    parser.add_argument(
        "--compose",
        default=os.fspath(COMPOSE_PATH),
        help="Compose file to rewrite (defaults to the repository's).",
    )
    args = parser.parse_args(argv)

    manifest_path = Path(args.manifest)
    compose_path = Path(args.compose)
    agents = load_enabled_agents(manifest_path)
    current = compose_path.read_text(encoding="utf-8")
    expected = build_expected(current, render_regions(agents))

    if args.check:
        if current != expected:
            print(
                f"{compose_path} is out of sync with {manifest_path}.\n"
                "Run: python default_agents/render_compose.py",
                file=sys.stderr,
            )
            return 1
        print(f"{compose_path} is in sync with {manifest_path}.")
        return 0

    if current == expected:
        print(f"{compose_path} already up to date.")
        return 0
    compose_path.write_text(expected, encoding="utf-8")
    print(f"Wrote generated default-agent section to {compose_path}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
