from typing import AsyncIterator, Callable, Protocol, runtime_checkable

from common.dto import DeliveryEvent, InternalEvent, SSEEvent


@runtime_checkable
class EventPublisher(Protocol):
    async def emit(self, event: DeliveryEvent) -> None: ...
    async def emit_internal(self, event: InternalEvent) -> None: ...
    def register_internal_handler(self, event_type: str, handler: Callable) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...


@runtime_checkable
class SSETransport(Protocol):
    async def connect(
        self, room_id: str, connection_id: str
    ) -> AsyncIterator[dict]: ...
    async def disconnect(self, connection_id: str) -> None: ...
    def is_cancelled(self, message_id: str) -> bool: ...
    async def mark_cancelled(self, message_id: str) -> None: ...
    def set_draining(self, draining: bool) -> None: ...
    async def start_cancellation_watcher(self) -> None: ...


__all__ = ["EventPublisher", "SSETransport"]
