from typing import Any, Protocol, TypeVar, runtime_checkable

from common.dto import AgentInfo, QueryFilter, RoomInfo

T = TypeVar("T")


@runtime_checkable
class CrudRepository(Protocol[T]):
    async def get(self, entity_id: str) -> T | None: ...
    async def list(self, filters: QueryFilter | None = None) -> list[T]: ...
    async def create(self, entity: T) -> T: ...
    async def update(self, entity_id: str, entity: T) -> T: ...
    async def delete(self, entity_id: str) -> bool: ...


@runtime_checkable
class AgentRepository(Protocol):
    async def get(self, agent_id: str) -> AgentInfo | None: ...
    async def list(self, filters: QueryFilter | None = None) -> list[AgentInfo]: ...
    async def save(self, agent: AgentInfo) -> AgentInfo: ...
    async def delete(self, agent_id: str) -> bool: ...


@runtime_checkable
class RoomRepository(Protocol):
    async def get(self, room_id: str) -> RoomInfo | None: ...
    async def list(self, filters: QueryFilter | None = None) -> list[RoomInfo]: ...
    async def save(self, room: RoomInfo) -> RoomInfo: ...
    async def delete(self, room_id: str) -> bool: ...


@runtime_checkable
class TaskRepository(Protocol):
    async def get(self, task_id: str) -> dict[str, Any] | None: ...
    async def list(self, filters: QueryFilter | None = None) -> list[dict[str, Any]]: ...
    async def save(self, task: dict[str, Any]) -> dict[str, Any]: ...
    async def delete(self, task_id: str) -> bool: ...


__all__ = [
    "AgentRepository",
    "CrudRepository",
    "RoomRepository",
    "TaskRepository",
]
