from datetime import datetime
from typing import Protocol, runtime_checkable


@runtime_checkable
class AgentRepository(Protocol):
    async def get_by_id(self, agent_id: str) -> dict | None: ...
    async def get_by_ids(self, agent_ids: list[str]) -> list[dict]: ...
    async def get_by_provider(self, provider_id: str) -> list[dict]: ...
    async def get_public(self, limit: int = 50) -> list[dict]: ...
    async def upsert(self, agent_id: str, data: dict) -> None: ...
    async def delete(self, agent_id: str) -> bool: ...
    async def update_health(self, agent_id: str, healthy: bool) -> None: ...
    async def mark_hub_agents_offline(self, hub_id: str) -> int: ...


@runtime_checkable
class RoomRepository(Protocol):
    async def get_by_id(self, room_id: str) -> dict | None: ...
    async def get_by_owner(self, owner_id: str) -> list[dict]: ...
    async def create(self, room: dict) -> str: ...
    async def update(self, room_id: str, updates: dict) -> bool: ...
    async def delete(self, room_id: str) -> bool: ...


@runtime_checkable
class MessageRepository(Protocol):
    async def save_user_message(self, message: dict) -> str: ...
    async def save_agent_message(self, message: dict) -> str: ...
    async def get_by_id(self, message_id: str) -> dict | None: ...
    async def get_by_ids(self, message_ids: list[str]) -> list[dict]: ...
    async def get_for_room(
        self, room_id: str, limit: int, before: datetime | None = None
    ) -> list[dict]: ...
    async def get_thread(self, parent_message_id: str) -> list[dict]: ...
    async def update_status(self, message_id: str, status: str, **fields) -> bool: ...


@runtime_checkable
class RunRepository(Protocol):
    async def create(self, run: dict) -> str: ...
    async def get_by_id(self, run_id: str) -> dict | None: ...
    async def get_for_room(self, room_id: str) -> list[dict]: ...
    async def update_state(self, run_id: str, state: str, **fields) -> bool: ...
    async def get_diverged(self, limit: int) -> list[dict]: ...


@runtime_checkable
class RunEventRepository(Protocol):
    async def append(self, run_id: str, event: dict) -> str: ...
    async def get_for_run(self, run_id: str) -> list[dict]: ...
    async def get_latest(self, run_id: str) -> dict | None: ...


@runtime_checkable
class HITLRepository(Protocol):
    async def create(self, request: dict) -> str: ...
    async def get_by_id(self, request_id: str) -> dict | None: ...
    async def get_pending_for_room(self, room_id: str) -> list[dict]: ...
    async def resolve(self, request_id: str, response: dict) -> bool: ...


@runtime_checkable
class MemoryRepository(Protocol):
    async def get_room_memory(self, room_id: str) -> dict | None: ...
    async def upsert_room_memory(self, room_id: str, memory: dict) -> None: ...
    async def get_user_memories(self, user_id: str) -> list[dict]: ...
    async def delete_room_memory(self, room_id: str) -> bool: ...


@runtime_checkable
class HubRepository(Protocol):
    async def get_by_id(self, hub_id: str) -> dict | None: ...
    async def get_by_owner(self, owner_id: str) -> list[dict]: ...
    async def upsert(self, hub_id: str, data: dict) -> None: ...
    async def update_heartbeat(self, hub_id: str) -> None: ...
    async def get_stale(self, threshold: datetime) -> list[dict]: ...


__all__ = [
    "AgentRepository",
    "HITLRepository",
    "HubRepository",
    "MemoryRepository",
    "MessageRepository",
    "RoomRepository",
    "RunEventRepository",
    "RunRepository",
]
