from collections.abc import AsyncIterator
from types import TracebackType
from typing import Any, Protocol, runtime_checkable

from common.dto import VectorRecord, VectorSearchResult


@runtime_checkable
class MongoDAL(Protocol):
    def collection(self, name: str) -> "MongoCollection": ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class MongoChangeStream(Protocol):
    async def __aenter__(self) -> AsyncIterator[dict]: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool | None: ...


@runtime_checkable
class MongoCollection(Protocol):
    async def find_one(self, query: dict, **kwargs) -> dict | None: ...
    async def find(self, query: dict, **kwargs) -> list[dict]: ...
    async def find_one_and_update(
        self, query: dict, update: dict | list[dict], **kwargs
    ) -> dict | None: ...
    async def insert_one(self, document: dict) -> str: ...
    async def insert_many(self, documents: list[dict]) -> list[str]: ...
    async def update_one(
        self, query: dict, update: dict | list[dict], **kwargs
    ) -> bool: ...
    async def replace_one(
        self, query: dict, replacement: dict, **kwargs
    ) -> bool: ...
    async def update_many(self, query: dict, update: dict) -> int: ...
    async def delete_one(self, query: dict) -> bool: ...
    async def delete_many(self, query: dict) -> int: ...
    async def count(self, query: dict) -> int: ...
    async def aggregate(self, pipeline: list[dict]) -> list[dict]: ...
    async def create_index(self, keys: list[tuple], **kwargs) -> str: ...
    async def create_indexes(self, indexes: list, **kwargs) -> list[str]: ...
    async def bulk_write(self, operations: list, **kwargs) -> Any: ...
    async def distinct(self, key: str, query: dict | None = None) -> list: ...
    async def find_one_by_stable_or_native_id(
        self, stable_id_field: str, id_value: str
    ) -> dict | None: ...
    def watch(
        self, pipeline: list[dict] | None = None, **kwargs
    ) -> MongoChangeStream: ...


@runtime_checkable
class RedisKV(Protocol):
    @property
    def is_connected(self) -> bool: ...
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> bool: ...
    async def increment(self, key: str, amount: int = 1) -> int: ...
    async def setnx(self, key: str, value: str, ttl: int) -> bool: ...
    async def exists(self, key: str) -> bool: ...
    async def ping(self) -> bool: ...
    async def close(self) -> None: ...


@runtime_checkable
class RedisPubSub(Protocol):
    async def publish(self, channel: str, message: str) -> None: ...
    async def subscribe(self, channel: str) -> AsyncIterator[str]: ...
    async def ping(self) -> bool: ...
    async def close(self) -> None: ...


@runtime_checkable
class RedisStreams(Protocol):
    @property
    def is_connected(self) -> bool: ...
    async def xadd(
        self, stream: str, fields: dict, maxlen: int | None = None
    ) -> str: ...
    async def xread(
        self, streams: dict, block: int = 0, count: int = 100
    ) -> list[dict]: ...
    async def ping(self) -> bool: ...
    async def close(self) -> None: ...


@runtime_checkable
class VectorDAL(Protocol):
    async def search(
        self, index: str, vector: list[float], top_k: int, filter: dict | None = None
    ) -> list[VectorSearchResult]: ...
    async def upsert(self, index: str, records: list[VectorRecord]) -> None: ...
    async def delete(self, index: str, ids: list[str]) -> None: ...
    async def delete_by_filter(self, index: str, filter: dict) -> None: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class ObjectStorageDAL(Protocol):
    async def put(self, key: str, data: bytes, content_type: str = "") -> str: ...
    async def put_file(
        self,
        key: str,
        file_data: Any,
        content_type: str = "",
        content_length: int | None = None,
    ) -> str: ...
    async def get_text(self, key: str) -> str | None: ...
    async def get_presigned_url(
        self, key: str, ttl: int = 3600, filename: str | None = None
    ) -> str: ...
    async def delete(self, key: str) -> bool: ...
    async def delete_prefix(self, prefix: str) -> int: ...
    def get_public_url(self, key: str) -> str: ...
    async def head(self, key: str) -> dict | None: ...


@runtime_checkable
class DistributedLock(Protocol):
    async def acquire(self, key: str, owner: str, ttl: int = 60) -> bool: ...
    async def release(self, key: str, owner: str) -> bool: ...
    async def renew(self, key: str, owner: str, ttl: int = 60) -> bool: ...


@runtime_checkable
class LeaderElector(Protocol):
    async def try_acquire(
        self, job_name: str, ttl: int = 60, *, ttl_seconds: int | None = None
    ) -> bool: ...
    async def renew(
        self, job_name: str, ttl: int = 60, *, ttl_seconds: int | None = None
    ) -> bool: ...
    async def release(self, job_name: str) -> None: ...
    async def release_all(self, job_names: list[str]) -> None: ...


@runtime_checkable
class IndexRegistry(Protocol):
    def register(
        self, module_name: str, collection: str, index_spec: list[tuple], **kwargs
    ) -> None: ...
    async def ensure_all(self) -> None: ...


__all__ = [
    "DistributedLock",
    "IndexRegistry",
    "LeaderElector",
    "MongoChangeStream",
    "MongoCollection",
    "MongoDAL",
    "ObjectStorageDAL",
    "RedisKV",
    "RedisPubSub",
    "RedisStreams",
    "VectorDAL",
]
