from collections.abc import AsyncIterator, Callable
from typing import Protocol, runtime_checkable

from common.dto import DeliveryEvent, InternalEvent
from common.protocols.json_types import JsonValue


@runtime_checkable
class EventPublisher(Protocol):
    async def emit(self, event: DeliveryEvent) -> None: ...
    async def emit_internal(
        self,
        event: InternalEvent,
        *,
        wait_for_local_handlers: bool = False,
        broadcast: bool = True,
    ) -> None: ...
    def register_internal_handler(self, event_type: str, handler: Callable) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...


@runtime_checkable
class SSETransport(Protocol):
    def connect(self, room_id: str, connection_id: str) -> AsyncIterator[dict]: ...
    async def disconnect(self, connection_id: str) -> None: ...
    def is_cancelled(self, message_id: str) -> bool: ...
    async def mark_cancelled(self, message_id: str) -> None: ...
    def set_draining(self, draining: bool) -> None: ...
    async def start_cancellation_watcher(self) -> None: ...


@runtime_checkable
class SSEConnectionLike(Protocol):
    connection_id: str
    is_active: bool

    async def get_message(self, timeout: float | None = None) -> str: ...


@runtime_checkable
class SSERouteTransport(Protocol):
    async def add_connection(self, room_id: str) -> SSEConnectionLike: ...
    async def remove_connection(self, room_id: str, connection_id: str) -> None: ...
    def get_room_status(self, room_id: str) -> dict[str, JsonValue]: ...


__all__ = ["EventPublisher", "SSEConnectionLike", "SSERouteTransport", "SSETransport"]
