from datetime import datetime
from typing import Any, Protocol, runtime_checkable

from common.dto import RoomTimelinePage, TimelinePosition, UserMessageInsertResult


@runtime_checkable
class AgentRepository(Protocol):
    async def get_by_id(self, agent_id: str) -> dict | None: ...
    async def get_by_ids(self, agent_ids: list[str]) -> list[dict]: ...
    async def get_by_provider(self, provider_id: str) -> list[dict]: ...
    async def get_by_source(self, source: str) -> list[dict]: ...
    async def get_public(self, limit: int = 50) -> list[dict]: ...
    async def upsert(self, agent_id: str, data: dict) -> None: ...
    async def delete(self, agent_id: str) -> bool: ...
    async def update_health(self, agent_id: str, healthy: bool) -> None: ...
    async def mark_agents_inactive(
        self, agent_ids: list[str], *, source: str
    ) -> int: ...
    async def mark_hub_agents_offline(self, hub_id: str) -> int: ...
    async def count_hub_agents(self, hub_id: str) -> tuple[int, int]: ...
    async def increment_agent_call_count(
        self, agent_id: str, *, success: bool
    ) -> None: ...
    async def find_by_normalized_url(
        self, normalized_url: str, provider_id: str | None = None
    ) -> dict | None: ...
    async def list_visible(
        self,
        *,
        user_id: str | None = None,
        active_only: bool = False,
        agent_ids: list[str] | None = None,
        query: dict | None = None,
        limit: int = 0,
    ) -> list[dict]: ...
    async def text_search(
        self, agent_ids: list[str], query: str, limit: int
    ) -> list[dict]: ...
    async def update(self, agent_id: str, updates: dict) -> dict | None: ...
    async def public_url_exists(self, subdomain: str, base_domain: str) -> bool: ...
    async def upsert_hub_agent(
        self, hub_id: str, local_agent_id: str, data: dict
    ) -> str: ...
    async def prune_missing_hub_agents(
        self, hub_id: str, active_agent_ids: list[str]
    ) -> int: ...
    async def activate_agents(self, agent_ids: list[str]) -> int: ...


@runtime_checkable
class RoomRepository(Protocol):
    async def get_by_id(self, room_id: str) -> dict | None: ...
    async def get_by_owner(self, owner_id: str) -> list[dict]: ...
    async def create(self, room: dict) -> str: ...
    async def update(self, room_id: str, updates: dict) -> bool: ...
    async def update_fields(self, room_id: str, updates: dict) -> dict | None: ...
    async def set_membership(
        self,
        room_id: str,
        *,
        agent_set: dict[str, str],
        membership_origin: str,
        membership_origin_status: str,
        source_group_id: str | None = None,
        source_group_name: str | None = None,
    ) -> dict | None: ...
    async def delete(self, room_id: str) -> bool: ...


@runtime_checkable
class QuoteRepository(Protocol):
    async def insert(self, snippet: dict | Any) -> str: ...
    async def get_by_id(self, quote_id: str) -> dict | None: ...
    async def delete_by_id(self, quote_id: str) -> bool: ...
    async def delete_for_room(self, room_id: str) -> int: ...


@runtime_checkable
class MessageRepository(Protocol):
    async def save_user_message(self, message: dict) -> str: ...
    async def get_user_message_by_idempotency_key(
        self, room_id: str, client_request_id: str
    ) -> dict | None: ...
    async def insert_user_message_idempotently(
        self, document: dict
    ) -> UserMessageInsertResult: ...
    async def save_agent_message(self, message: dict) -> str: ...
    async def get_by_id(self, message_id: str) -> dict | None: ...
    async def get_user_message_by_id(self, message_id: str) -> dict | None: ...
    async def get_agent_message_by_id(self, message_id: str) -> dict | None: ...
    async def is_message_cancelled(self, message_id: str) -> bool: ...
    async def update_user_message(self, message_id: str, updates: dict) -> bool: ...
    async def update_agent_message(self, message_id: str, updates: dict) -> bool: ...
    async def update_agent_message_if_not_terminal(
        self, message_id: str, updates: dict, terminal_states: list[str]
    ) -> bool: ...
    async def count_agent_messages(self, query: dict) -> int: ...
    async def get_by_ids(self, message_ids: list[str]) -> list[dict]: ...
    async def get_for_room(
        self, room_id: str, limit: int, before: datetime | None = None
    ) -> list[dict]: ...
    async def get_timeline_page(
        self,
        room_id: str,
        *,
        limit: int,
        before: TimelinePosition | None,
    ) -> RoomTimelinePage: ...
    async def get_thread(self, parent_message_id: str) -> list[dict]: ...
    async def update_status(self, message_id: str, status: str, **fields) -> bool: ...
    async def delete_for_room(self, room_id: str) -> dict[str, int]: ...
    async def get_user_messages_for_room(
        self, room_id: str, limit: int = 100, before: datetime | None = None
    ) -> list[dict]: ...
    async def get_agent_messages_for_room(
        self, room_id: str, limit: int = 100, before: datetime | None = None
    ) -> list[dict]: ...
    async def get_agent_messages_by_related_message_id(
        self, related_message_id: str
    ) -> list[dict]: ...
    async def get_agent_task_messages_for_user(
        self, user_id: str, states: list[str]
    ) -> list[dict]: ...
    async def get_task_messages_for_room(
        self, room_id: str, limit: int
    ) -> list[dict]: ...
    async def get_pending_task_messages_for_user(
        self, user_id: str, states: list[str]
    ) -> list[dict]: ...


@runtime_checkable
class RunRepository(Protocol):
    async def find(
        self, query: dict, *, sort: list[tuple[str, int]] | None = None, limit: int = 0
    ) -> list[dict]: ...
    async def find_one(self, query: dict, **kwargs) -> dict | None: ...
    async def create(self, run: dict) -> str: ...
    async def insert_one(self, document: dict) -> str: ...
    async def update_one(self, query: dict, update: dict) -> bool: ...
    async def get_by_id(self, run_id: str) -> dict | None: ...
    async def get_for_room(self, room_id: str) -> list[dict]: ...
    async def update_state(self, run_id: str, state: str, **fields) -> bool: ...
    async def get_diverged(self, limit: int) -> list[dict]: ...


@runtime_checkable
class RunEventRepository(Protocol):
    async def find_one(
        self, query: dict, *, sort: list[tuple[str, int]] | None = None
    ) -> dict | None: ...
    async def insert_one(self, document: dict) -> str: ...
    async def append(self, run_id: str, event: dict) -> str: ...
    async def get_for_run(self, run_id: str) -> list[dict]: ...
    async def get_latest(self, run_id: str) -> dict | None: ...


@runtime_checkable
class HITLRepository(Protocol):
    async def create(self, request: dict) -> str: ...
    async def get_by_id(self, request_id: str) -> dict | None: ...
    async def get_pending_for_room(self, room_id: str) -> list[dict]: ...
    async def resolve(self, request_id: str, response: dict) -> bool: ...


@runtime_checkable
class MemoryRepository(Protocol):
    async def get_room_memory(self, room_id: str) -> dict | None: ...
    async def upsert_room_memory(self, room_id: str, memory: dict) -> None: ...
    async def get_user_memories(self, user_id: str) -> list[dict]: ...
    async def delete_room_memory(self, room_id: str) -> bool: ...
    async def create_room_memory(self, memory: dict) -> str: ...
    async def ensure_room_memory(self, room_id: str, defaults: dict) -> dict: ...
    async def get_room_memory_by_memory_id(self, memory_id: str) -> dict | None: ...
    async def update_room_memory_by_room_id(
        self, room_id: str, updates: dict
    ) -> bool: ...
    async def update_room_memory_by_memory_id(
        self, memory_id: str, updates: dict
    ) -> bool: ...
    async def delete_room_memory_by_memory_id(self, memory_id: str) -> bool: ...
    async def push_and_trim_conversation_turn(
        self,
        room_id: str,
        turn: dict,
        *,
        max_turns: int,
        summary_stub: str,
        max_summary_chars: int,
    ) -> tuple[bool, bool]: ...
    async def push_and_trim_conversation_turn_if_absent(
        self,
        room_id: str,
        turn: dict,
        *,
        turn_id: str,
        max_turns: int,
        summary_stub: str,
        max_summary_chars: int,
    ) -> tuple[bool, bool, bool]: ...
    async def update_turn_notes(
        self, room_id: str, turn_id: str, turn_notes: dict
    ) -> bool: ...
    async def get_room_summary_projection(self, room_id: str) -> dict | None: ...
    async def update_room_summary_atomic(
        self,
        room_id: str,
        room_summary: dict,
        *,
        new_facts: list[dict] | None = None,
        max_facts: int = 50,
    ) -> bool: ...
    async def compact_turns_bulk(
        self, room_id: str, compacted_turns: list[dict]
    ) -> bool: ...
    async def list_room_ids_with_memory(
        self, limit: int | None = None
    ) -> list[str]: ...


@runtime_checkable
class ContentStorageRepository(Protocol):
    async def upsert_full_content(
        self,
        *,
        document_id: str,
        room_id: str,
        turn_id: str,
        content: str,
        content_type: str,
        content_hash: str,
        stored_at: datetime,
        turn_timestamp: datetime | str | None = None,
        expires_at: datetime | None = None,
        turn_notes: dict | None = None,
    ) -> str: ...
    async def get_content_by_document_id(self, document_id: str) -> dict | None: ...
    async def get_content_by_turn_id(
        self, room_id: str, turn_id: str
    ) -> dict | None: ...
    async def delete_content_by_turn_id(self, room_id: str, turn_id: str) -> bool: ...
    async def delete_content_by_room_id(self, room_id: str) -> int: ...
    async def get_content_stats_for_room(self, room_id: str) -> dict: ...
    async def text_search(
        self,
        room_id: str,
        query: str,
        limit: int = 50,
        skip: int = 0,
    ) -> list[dict]: ...
    async def scan_text_search(
        self, room_id: str, query: str, limit: int
    ) -> list[dict]: ...
    async def hydrate_turn_content(
        self, room_id: str, turn_ids: list[str]
    ) -> list[dict]: ...


@runtime_checkable
class HubRepository(Protocol):
    async def get_by_id(self, hub_id: str) -> dict | None: ...
    async def get_by_owner(self, owner_id: str) -> list[dict]: ...
    async def upsert(self, hub_id: str, data: dict) -> None: ...
    async def update_heartbeat(self, hub_id: str) -> None: ...
    async def get_stale(self, threshold: datetime) -> list[dict]: ...
    async def list_online_hubs_for_liveness(self) -> list[dict]: ...
    async def list_offline_hubs_for_recovery(self, limit: int) -> list[dict]: ...
    async def update_hub_status(self, hub_id: str, **fields) -> None: ...
    async def update_hub_status_if_current(
        self, hub_id: str, connection_id: str, **fields
    ) -> bool: ...


@runtime_checkable
class HubResponseJournal(Protocol):
    async def ensure_indexes(self) -> None: ...
    async def create_or_get(self, event: dict) -> dict: ...
    async def claim_for_processing(
        self, journal_id: str, owner_id: str
    ) -> dict | None: ...
    async def mark_processed(
        self, journal_id: str, claim_token: str | None = None
    ) -> None: ...
    async def mark_dead_letter(self, journal_id: str, reason: str) -> None: ...
    async def find_replayable(self, limit: int = 100) -> list[dict]: ...


@runtime_checkable
class HubTaskOwnershipStore(Protocol):
    async def ensure_indexes(self) -> None: ...
    async def claim_or_refresh(
        self, aliases: dict, owner_id: str, lease_token: str
    ) -> dict: ...
    async def resolve_owner(self, alias: str) -> dict | None: ...
    async def release(self, alias: str, owner_id: str | None = None) -> None: ...


__all__ = [
    "AgentRepository",
    "ContentStorageRepository",
    "HITLRepository",
    "QuoteRepository",
    "HubRepository",
    "HubResponseJournal",
    "HubTaskOwnershipStore",
    "MemoryRepository",
    "MessageRepository",
    "RoomRepository",
    "RunEventRepository",
    "RunRepository",
]
