from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class A2ATaskReader(Protocol):
    async def get(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list(self, *args: Any, **kwargs: Any) -> Any: ...


@runtime_checkable
class AgentGroupStore(Protocol):
    async def add_agent_group(self, agent_group: Any) -> Any: ...
    async def delete_agent_group(self, group_id: str) -> Any: ...
    async def get_agent_group_by_id(self, group_id: str) -> Any: ...
    async def get_agent_groups_by_owner(self, owner_id: str) -> Any: ...
    async def update_agent_group(self, group_id: str, updates: dict) -> Any: ...


__all__ = ["A2ATaskReader", "AgentGroupStore"]
