from typing import Protocol, runtime_checkable


@runtime_checkable
class A2ATaskReader(Protocol):
    async def get_pending_task_messages_for_user(
        self, user_id: str, non_terminal_states: list[str]
    ) -> list[object]: ...
    async def get_room_agent_message_by_message_id(self, message_id: str) -> object: ...
    async def get_task_messages_for_room(
        self, room_id: str, *, limit: int = 50
    ) -> list[object]: ...
    async def get_room_user_message_by_message_id(self, message_id: str) -> object: ...
    async def get_room_by_room_id(self, room_id: str) -> object: ...


@runtime_checkable
class AgentGroupStore(Protocol):
    async def add_agent_group(self, agent_group: object) -> object: ...
    async def delete_agent_group(self, group_id: str) -> object: ...
    async def get_agent_group_by_id(self, group_id: str) -> object: ...
    async def get_agent_groups_by_owner(self, owner_id: str) -> list[object]: ...
    async def update_agent_group(
        self, group_id: str, updates: dict[str, object]
    ) -> object: ...


__all__ = ["A2ATaskReader", "AgentGroupStore"]
